#!/bin/sh

# Copyright (c) 2017 Luca Pizzamiglio
# Copyright (c) 2005-2012 Douglas Barton, All rights reserved

PM_SUBR_DIR="."

if [ ! -r ${PM_SUBR_DIR}/portmaster.subr ]; then
	echo -e "\n===>>> portmaster subroutine not found"
	exit 1
fi
. ${PM_SUBR_DIR}/portmaster.subr

pm_init_global_vars NO_PACKAGES

PM_UPDATE_LIST=shells/bash
